#该action仅表征有新构建，如果为发布tag仅表征任一工具有新发布

name: Windows-Qt6.5.1-Build-Release
on:
  push:
  workflow_dispatch:
#  push:
#    paths:
#      - 'thirdTarget_I2CTool/**'
#      - '.github/workflows/Windows-Qt6.5.1.yml'
#  pull_request:
#    paths:
#      - 'thirdTarget_I2CTool/**'
#      - '.github/workflows/Windows-Qt6.5.1.yml'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - qt_ver: 6.5.3
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    env:
      targetName: ComTool.exe
      fileName: ComTool
    steps:
      #准备仓库
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 50
          fetch-tags: true

      #准备编译链
      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.10.2
      #准备Qt
      - name: Install qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cache: ${{steps.cache-qt.outputs.cache-hit}}
          modules: 'qt5compat qtmultimedia qtshadertools qtimageformats qtspeech qt3d qtscxml qtserialport qthttpserver qtwebsockets qtscxml'
      #准备boost
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: boost-python
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true
      #编译与打包
      - name: Msvc build & Package
        id: build
        shell: cmd
        run: |
          call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" ${{ matrix.msvc_arch }}
          ninja --version
          mkdir build
          cd build
          cmake -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DBoost_NO_SYSTEM_PATHS=ON -DBoost_LIBRARY_DIR_RELEASE=D:/a/WirelessMonitor/WirelessMonitor/vcpkg/installed/x64-windows/lib -DCMAKE_PREFIX_PATH=D:/a/WirelessMonitor/Qt/${{ matrix.qt_ver }}/msvc2019_64/lib/cmake/;D:/a/WirelessMonitor/WirelessMonitor/vcpkg/installed/x64-windows-release/share/ -DCMAKE_TOOLCHAIN_FILE=D:/a/WirelessMonitor/WirelessMonitor/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -GNinja ..                
          
          setlocal enabledelayedexpansion
          set /p bat_version=<bat_version
          echo bat_version is %bat_version%
          echo "bat_version=$bat_version" >> $GITHUB_ENV
          echo "::set-output name=bat_version::$bat_version"
          
          cmake --build . --target all --config Release --parallel
          cmake --build . --target package
          echo winSdkDir=%WindowsSdkDir% >> %GITHUB_ENV%
          echo winSdkVer=%WindowsSdkVersion% >> %GITHUB_ENV%
          echo vcToolsInstallDir=%VCToolsInstallDir% >> %GITHUB_ENV%
          echo vcToolsRedistDir=%VCToolsRedistDir% >> %GITHUB_ENV%


      #编译失败时打开调试接口
      - name: Setup tmate session if failed
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
          timeout-minutes: 300

      #发布Release
      - name: New Release1
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: D:/a/WirelessMonitor/WirelessMonitor/build/xtxTools-ComTool.zip
          asset_name: ComTool_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true

      #发布Release
      - name: New Release2
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: D:/a/WirelessMonitor/WirelessMonitor/build/xtxTools-I2CTool.zip
          asset_name: I2CTool_${{ github.ref_name }}_${{ matrix.qt_arch }}_Qt${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true


